FROM quay.io/pawsey/mpich-base:3.4.3_ubuntu24.04

# Build Python 3.13 from source and install additional dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    libgdbm-dev \
    libc6-dev \
    libnsl-dev \
    tk-dev \
    lzma-dev \
    zlib1g-dev \
    wget \
    git \
    wcslib-dev && \
    wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz && \
    tar xzf Python-3.13.0.tgz && \
    cd Python-3.13.0 && \
    ./configure --enable-optimizations --prefix=/usr/local && \
    make -j$(nproc) && \
    make install && \
    cd .. && \
    rm -rf Python-3.13.0 Python-3.13.0.tgz && \
    update-alternatives --install /usr/bin/python python /usr/local/bin/python3.13 1 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.13 1 && \
    /usr/local/bin/python3.13 -m pip install --upgrade pip && \
    rm -rf /var/lib/apt/lists/*

# Copy and install Python requirements
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --break-system-packages -r /tmp/requirements.txt

# Build and install Sofia2
RUN cd /tmp && \
    git clone https://gitlab.com/SoFiA-Admin/SoFiA-2.git && \
    cd SoFiA-2 && \
    make OMP=true && \
    make install DESTDIR=/usr/bin && \
    cd .. && \
    rm -rf SoFiA-2
